# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('camera_type', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('photography_style', models.CharField(choices=[('MONO', 'Monochrome'), ('MACRO', 'Macro'), ('MICRO', 'Micro'), ('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=255)),
                ('social_status', models.CharField(choices=[('PEASANT', 'Peasant'), ('KNIGHT', 'Knight'), ('MANATARMS', 'Man-at-Arms'), ('ROYALTY', 'Royalty'), ('BANDIT', 'Bandit'), ('BARBARIAN', 'Barbarian'), ('COW', 'Cow')], default='COW', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
