# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='age',
            field=models.IntegerField(default='25'),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(default='Polaroid', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='job',
            field=models.CharField(default='Developer', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(default='Seattle, WA', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='url',
            field=models.URLField(default='github.com/jjfeore'),
        ),
    ]
