# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170621_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
