# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imager_profile', '0003_auto_20170621_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_published', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(default=datetime.date.today)),
                ('img_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('published', models.CharField(choices=[('PRI', 'private'), ('SHA', 'shared'), ('PUB', 'public')], default='private', max_length=3)),
                ('cover', models.ImageField(null=True, upload_to='photos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='imager_profile.ImagerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('date_published', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(default=datetime.date.today)),
                ('img_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('published', models.CharField(choices=[('PRI', 'private'), ('SHA', 'shared'), ('PUB', 'public')], default='PRI', max_length=3)),
                ('image', models.ImageField(null=True, upload_to='photos')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='imager_profile.ImagerProfile')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='photoset',
            field=models.ManyToManyField(related_name='in_album', to='imager_images.Photo'),
        ),
    ]
