# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20170714_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_published',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
